### ISSUE TITLE
Small nether border causes incorrect bed respawn

### ISSUE THREAD

**Issue by Sukadia** [pop4959/ChunkyBorder#60] opened 2023-07-18 04:01 UTC
Hey; I've had my server setup such that the overworld is a 10000 radius circle and the nether, being 1/8 of that, is 1250.
However whenever you die in the Nether (I believe the end as well), when your bed location in the overworld is outside of the border in the dimension you died in, you'll be teleported to, what I believe is, somewhere on the Nether border's limits; not the overworld's.
Basically, you have a bed respawn point at x5000, z0, you'll respawn at x1250 z0 (or something along those lines).

Current workaround is setting nether and overworld radiuses to be the same.

**Comment by pop4959** [comment] 2023-07-18 04:18
Chunky Border doesn't set bed locations for players. Are you sure you don't have another plugin doing this?

**Comment by Sukadia** [comment] 2023-07-18 04:25
I'm using the Fabric version, and I do confirm it is definitely the mod. Removing ChunkyBorder or upping the radius to fit the bed location fixes the problem. If you'd like I can send a video demonstrating it.

**Comment by pop4959** [comment] 2023-07-25 00:08
Yep that would be great if you can show a video (or just give steps) to demonstrate. I can try to take a look when I get a chance.

**Comment by pop4959** [comment] 2023-11-06 04:31
I found some time to test this and unfortunately I cannot reproduce this edge case which I believe to be when setting a world border in the nether that is smaller than the location of a bed respawn location in the overworld based on the video. It sends me to my bed every time, even though it would be outside of the nether border area.

Going to assume that this is either caused by another mod, or that this was fixed in a more recent Minecraft update, but if you are still having issues please join the Discord server and in that case we can continue to troubleshoot and possibly re-open this issue should it be a concern again. Thank you!

**Closed by pop4959** 2023-11-06 04:31 UTC
Labels: bug

**Comment by dalbitresb12** [comment] 2024-11-20 17:30
Hi @pop4959. Sorry to revive this thread.

I just hit this bug in a server I have on Minecraft 1.20.1 with Fabric. I was able to reproduce it in a clean server with only Chunky and Chunky Border installed (and Fabric API). It appears it has been fixed in a later version with #68. I wanted to try to backport this fix to MC 1.20, test it on my server and if it works, I could make a PR so that this new version can be published to Modrinth for everyone to use. Would you be interested in this?
