### ISSUE TITLE
Worldborder does not display currently on Pl3xMap

### ISSUE THREAD

**Issue by AshiroKun** [pop4959/ChunkyBorder#35] opened 2021-12-19 14:52 UTC
Hi

Currently when using pl3xmap, the right side line for the world border does not appear. I spoke to the developer of pl3xmap and they stated its an issue to do with chunky or chunkyborder. 

I am not sure if this bug happens on dynmap or any other 3d viewing platform.
![1](https://user-images.githubusercontent.com/40526576/146679392-e6e23184-254b-4cc7-b68e-d3f51e89d883.PNG)

**Comment by pop4959** [comment] 2021-12-19 22:02
Can you provide more details on the versions you are using, etc. Sounds like other people are having this problem as well, though the code for the lines hasn't changed recently so I don't know why this would have broken.

**Comment by pop4959** [comment] 2021-12-19 22:05
Border file would also be appreciated.

**Comment by pop4959** [comment] 2021-12-21 05:32
Was able to reproduce this issue on the latest versions of Chunky and ChunkyBorder. Looks like it wasn't an issue in the previous release though.

**Comment by pop4959** [comment] 2021-12-21 06:30
This has been fixed in the latest dev builds of [Chunky](https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/) and [ChunkyBorder](https://ci.codemc.io/view/Author/job/pop4959/job/ChunkyBorder/). You will need to update to Squaremap however, if you have a Minecraft 1.18.1 server. If you are still running 1.17.1, you should be able to safely downgrade to Chunky 1.2.86 and ChunkyBorder 1.0.38 which did not have this issue.

**Closed by pop4959** 2021-12-21 06:30 UTC
Labels: bug
